### your site title here

title: Emir Cem Gezer
description: Robotics Researcher | University of Rhode Island

baseurl:  #name of GitHub repository
url: https://emircem.com #custom url to be used instead of GitHub repository
email: "emircem.gezer@gmail.com"


highlighter: rouge
markdown: kramdown

# Pagination
paginate: 4
permalink: /blog/:year/:title/
paginate_path: /blog/page:num/

# Social media links in footer
# facebook: "#"
twitter: "https://twitter.com/incebellipipo"
linkedin: "emircemgezer"
github: "incebellipipo"
scholar: "citations?user=tkd32OsAAAAJ"
# researchgate: "#"
orcid: "https://orcid.org/0000-0002-6223-9805"

highlighter: rouge
markdown: kramdown

# Tracker
analytics: G-WBF9GYFBXX

#optimization -> compress.html
compress_html:
  clippings: [html,div, p, ul, td, h1, h2, h3, h4,link, meta, footer, nav, img, header, hr, br, head, style, li, ul, ol, time, main, script, title]
  comments: ["<!-- ", " -->"]
  endings: [all]
  ignore:
    envs: [local]
  blanklines: false
  profile: false
  startings: []

#collection
collections:
  projects:
    output: true
    permalink: /projects/:path/

sass:
  sass_dir: /assets/css/_sass
  style: compressed

include:
  - _pages

exclude:
  - README.md
  - LICENSE.md

plugins:
  - jekyll-seo-tag
  - jekyll-paginate
  - jekyll-email-protect
  - jekyll-target-blank
